import { ThemeClass } from "../types";

const lightTheme: ThemeClass={
  
    "background": "bg-[#0a0f1e]",
    "surface": "bg-[#0d1526]",
    "inputBg": "bg-[#0f1629]",
    "cardBg": "bg-[#0d1526] border border-[#1e2d4a]",
    "border":"border border-[#1e2d4a]",
    "borderFocused": "border border-blue-600",
    "textPrimary": "text-slate-100",
    "textSecondary": "text-slate-300" ,
    "textMuted": "text-slate-500",
    "textPrice": "text-blue-400 font-bold",
    "textError": "text-red-500",
    "textSuccess": "text-emerald-500",
    "btnPrimary":"bg-blue-600 rounded-xl",
    "btnPrimaryText": "text-white font-bold",
    "btnOutline": "border border-blue-600 rounded-xl",
    "btnOutlineText": "text-blue-400 font-medium",
    "btnDisabled": "bg-slate-700 rounded-xl",
    "btnDisabledText": "text-slate-500",
    "iconDefault":"text-slate-400",
    "tabActive": "text-blue-500",
    "tabInactive":  "text-blue-500",
    "wishlistActive": "text-rose-500" ,
    "wishlistInactive": "text-slate-500" ,
    "starRating": "text-amber-400",
    "badge":"bg-blue-600 rounded-full", 
    "badgeText":"text-white text-xs font-bold",
    "pillActive": "bg-blue-600 rounded-full",
    "pillActiveText":"text-white text-xs font-medium",
    "pillInactive":"bg-[#0d1526] border border-[#1e2d4a] rounded-full",
    "pillIncativeText": "text-slate-500 text-xs",
    "successBg":"bg-emerald-950",
    "errorBg": "bg-red-950",
    "warningText": "text-amber-400",
    "overlay": "bg-black/60",
    "skeleton": "bg-[#162040]"
}

const darkTheme: ThemeClass={
    "background": "bg-white",
    "surface": "bg-slate-50",
    "inputBg": "bg-slate-100",
    "cardBg": "bg-white border border-slate-200",
    "border":"border border-slate-200",
    "borderFocused": "border border-blue-500",
    "textPrimary": "text-slate-900",
    "textSecondary": "text-slate-600" ,
    "textMuted": "text-slate-400",
    "textPrice": "text-blue-600 font-bold",
    "textError": "text-red-500",
    "textSuccess": "text-emerald-800",
    "btnPrimary":"bg-blue-600 rounded-xl",
    "btnPrimaryText": "text-white font-bold",
    "btnOutline": "border border-blue-600 rounded-xl",
    "btnOutlineText": "text-blue-600 font-medium",
    "btnDisabled": "bg-slate-200 rounded-xl",
    "btnDisabledText": "text-slate-400",
    "iconDefault":"text-slate-500",
    "tabActive": "text-blue-600",
    "tabInactive":  "text-slate-400",
    "wishlistActive": "text-rose-500" ,
    "wishlistInactive": "text-slate-400" ,
    "starRating": "text-amber-400",
    "badge":"bg-blue-600 rounded-full", 
    "badgeText":"text-white text-xs font-bold",
    "pillActive": "bg-blue-600 rounded-full",
    "pillActiveText":"text-white text-xs font-medium",
    "pillInactive":"bg-slate-100 border border-slate-200 rounded-full",
    "pillIncativeText": "text-slate-500 text-xs",
    "successBg":"bg-emerald-50",
    "errorBg": "bg-red-50",
    "warningText": "text-amber-500",
    "overlay": "bg-black/50",
    "skeleton": "bg-slate-200"
}

export {darkTheme, lightTheme}
