export interface ThemeClass {
  
    "background": string,
    "surface": string,
    "inputBg": string,
    "cardBg": string,
    "border": string,
    "borderFocused": string,
    "textPrimary": string,
    "textSecondary": string,
    "textMuted": string,
    "textPrice": string,
    "textError": string,
    "textSuccess": string,
    "btnPrimary": string,
    "btnPrimaryText": string,
    "btnOutline": string,
    "btnOutlineText": string,
    "btnDisabled": string,
    "btnDisabledText": string,
    "iconDefault": string,
    "tabActive": string,
    "tabInactive": string,
    "wishlistActive": string,
    "wishlistInactive": string,
    "starRating": string,
    "badge": string,
    "badgeText": string,
    "pillActive": string,
    "pillActiveText": string,
    "pillInactive": string,
    "pillIncativeText": string,
    "successBg": string,
    "errorBg": string,
    "warningText": string,
    "overlay": string,
    "skeleton": string
  
}